version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: metadata
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/metadata
      MONGO_URI: mongodb://mongo:27017/
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - mongo
      - redis
    ports:
      - "8000:8000"

  worker:
    build: ./backend
    command: celery -A app.celery_config.celery_app worker --loglevel=info --concurrency=2
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/metadata
      MONGO_URI: mongodb://mongo:27017/
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - backend
      - db
      - mongo
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
