repos:
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
    - id: detect-secrets
      args:
        - --baseline
        - .secrets.baseline
        - --exclude-files
        - (\.venv|node_modules|dist|build|\.git|agentic-api/test\.db)
      pass_filenames: false
