name: Secret Scan

on: [push, pull_request]

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run Gitleaks scan
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          scan-path: .
          args: detect --source . --no-git --report-format sarif --report-path gitleaks.sarif

      # Upload SARIF report to GitHub code scanning
      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      # Detect-secrets baseline verification
      - name: Detect-Secrets (baseline)
        run: |
          pipx install detect-secrets
          detect-secrets scan \
            --exclude-files '(\.venv|node_modules|dist|build|\.git|agentic-api/test\.db)' \
            > .secrets.tmp
          python - <<'PY'
          import json, sys
          with open('.secrets.tmp') as f: cur=json.load(f)
          if cur.get('results'):
              print("Potential secrets detected. Review .secrets.tmp")
              sys.exit(1)
          PY
