name: Secret Scan

on: [push, pull_request]

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run Gitleaks
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks.sarif --no-git

      # Upload SARIF report
      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      # Run detect-secrets
      - name: Detect-Secrets (baseline)
        run: |
          pipx install detect-secrets
          detect-secrets scan \
            --exclude-files '(\.venv|node_modules|dist|build|\.git|agentic-api/test\.db)' \
            > .secrets.tmp
          python - <<'PY'
          import json, sys
