name: Secret Scan

on: [push, pull_request]

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug paths
        run: |
          pwd && ls -la
          echo "Baseline present?"; test -f .secrets.baseline && echo YES || echo NO

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install detect-secrets
        run: python -m pip install --upgrade pip detect-secrets==1.5.0

      - name: Run detect-secrets (baseline compare)
        run: |
          if [ -f ".secrets.baseline" ]; then
            detect-secrets-hook \
              --baseline .secrets.baseline \
              --exclude-files '(\.venv|^venv/|node_modules|dist|build|\.git|Agentic-AI-platform/\.git|agentic-api/test\.db)'
          else
            echo "No .secrets.baseline found; skipping baseline compare."
          fi

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks-results.sarif

      - name: Upload SARIF to Code Scanning
        if: hashFiles('gitleaks-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-results.sarif
